version: '3.8'

services:
  # WAHA WhatsApp HTTP API Service
  waha:
    image: devlikeapro/waha
    container_name: waha
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - WAHA_API_KEY=${WAHA_API_KEY:-admin}
      - WAHA_DASHBOARD_USERNAME=${WAHA_DASHBOARD_USERNAME:-admin}
      - WAHA_DASHBOARD_PASSWORD=${WAHA_DASHBOARD_PASSWORD:-admin}
      - WHATSAPP_SWAGGER_USERNAME=${WHATSAPP_SWAGGER_USERNAME:-admin}
      - WHATSAPP_SWAGGER_PASSWORD=${WHATSAPP_SWAGGER_PASSWORD:-admin}
    volumes:
      - waha_sessions:/app/.sessions
    networks:
      - masjid-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/version"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Main Masjid Bot Application
  masjid-bot:
    build: .
    container_name: masjid-bot
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=3001
      - WAHA_BASE_URL=http://waha:3000
      - WAHA_API_KEY=${WAHA_API_KEY:-admin}
      - WA_SESSION_NAME=${WA_SESSION_NAME:-default}
      - N8N_WEBHOOK_URL=${N8N_WEBHOOK_URL}
      - ADMIN_NUMBERS=${ADMIN_NUMBERS}
      - GOOGLE_SHEETS_ID=${GOOGLE_SHEETS_ID}
      - GOOGLE_SHEETS_CREDENTIALS=${GOOGLE_SHEETS_CREDENTIALS}
      - WEBHOOK_URL=http://masjid-bot:3001/webhook/waha
    volumes:
      - ./logs:/app/logs
    depends_on:
      waha:
        condition: service_healthy
    networks:
      - masjid-network
    command: >
      sh -c "
        echo 'Waiting for WAHA service to be ready...' &&
        sleep 10 &&
        npm start
      "

  # Express Server for Webhooks and API
  masjid-server:
    build: .
    container_name: masjid-server
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=3002
      - WAHA_BASE_URL=http://waha:3000
      - WAHA_API_KEY=${WAHA_API_KEY:-admin}
      - WA_SESSION_NAME=${WA_SESSION_NAME:-default}
      - N8N_WEBHOOK_URL=${N8N_WEBHOOK_URL}
      - ADMIN_NUMBERS=${ADMIN_NUMBERS}
    volumes:
      - ./logs:/app/logs
    depends_on:
      - waha
      - masjid-bot
    networks:
      - masjid-network
    command: npm run server

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: masjid-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - waha
      - masjid-bot
      - masjid-server
    networks:
      - masjid-network

volumes:
  waha_sessions:
    driver: local

networks:
  masjid-network:
    driver: bridge